### PR TITLE
fix #1 Authentication

### LINKED ISSUE #1: Authentication requirements causes failure
My team currently uses Assembla to authenticate logging into our Jenkins. In the future, we will also probably be moving to JIRA authentication. This apparently causes this plugin to fail when trying to access Jenkins. Is there a fix for this?

### PR DESCRIPTION
**Pull request by kfiku**
#1 add auth feature

add some error raporting
fixing detecting if job starts
add 20s timeout to wait for job to start

### CODE REVIEW

**Comment by benmatselby** [comment]
@kfiku Can you please rebase against master, as there are conflicts.

**Comment by kfiku** [comment]
@benmatselby try now

**Comment by benmatselby** [comment]
Fantastic, merged this, thanks @kfiku

**Comment by kfiku** [comment]
No problem :) its for all of us. Enjoy

**Pull request merged**
