### PR TITLE
print job console output to new file

### PR DESCRIPTION
**Pull request by kfiku**
I think it can be useful feature. I use jenkins console output a lot and i think a lot of people will like it to.

### CODE REVIEW

**Comment by benmatselby** [comment]
Hi @kfiku 

Sorry about the delays, I've been offline for a few days. Will review this later today all being well. Thanks for the PR

**Comment by kfiku** [comment]
Hi @benmatselby 
No problem, give you some time for it.

**Comment by benmatselby** [comment]
@kfiku This doesn't seem to be working for me, the job does not build, and the debug just reports a POST message every second.

Will do some more testing when I get chance.

**Comment by kfiku** [comment]
@benmatselby give it a second, workflow is like this:
- get last job info and save last build number
- Jenkins.build_job(picked)
- run timer for 1 sec
- get last build info
- if last build number == saved before build last build number
  - run timer again
- else - means that new build was started
  - get job console output and add it to new file test
- check if job is still building 
  - run timeout again
- it build finished finish hole process

**Comment by benmatselby** [comment]
@kfiku 

Hi there. This is a nice edition, thanks for the PR. It is now merged. The issue for me is that I need to auth in order to build jobs. So I've had to put some checks in to make sure you have successfully kicked off a build otherwise Sublime Text will keep polling until you close the application, which isn't great.

Ideally, I need to sort out GH-1 now.

**Comment by kfiku** [comment]
@benmatselby it will be cool to have it, i can help you with this.

**Comment by benmatselby** [comment]
@kfiku I've had a quick try but Jenkins returns 403 straight away rather than a 401 to negotiate.

**Comment by kfiku** [comment]
look at #3 for me its working

**Pull request merged**
